// lib/categories.js

export const categories = [
  { name: "Home", href: "/" },
  { name: "Navbars", href: "/navbars" },
  { name: "Headers", href: "/headers" },
  { name: "Layouts", href: "/layouts" },
  { name: "Contents", href: "/contents" },
  { name: "CTAs", href: "/ctas" },
  { name: "Testimonials", href: "/testimonials" },
  { name: "Gallery", href: "/gallerys" },
  { name: "Blogs", href: "/blogs" },
  { name: "Events", href: "/events" },
  { name: "Logos", href: "/logos" },
  { name: "Banners", href: "/banners" },
  { name: "Products", href: "/products" },
  { name: "Portfolios", href: "/portfolios" },
  { name: "Stats", href: "/stats" },
  { name: "Pricings", href: "/pricings" },
  { name: "Comparisons", href: "/comparisons" },
  { name: "Timelines", href: "/timelines" },
  { name: "Teams", href: "/teams" },
  { name: "Careers", href: "/careers" },
  { name: "FAQs", href: "/faqs" },
  { name: "Contacts", href: "/contacts" },
  { name: "Footers", href: "/footers" },
  { name: "Forms", href: "/forms" },
  { name: "Sign Ups", href: "/signups" },
  { name: "Log Ins", href: "/logins" },
  { name: "Modals", href: "/modals" },
  { name: "Links", href: "/links" },
  { name: "Application Shells", href: "/applicationshells" },
  { name: "Description Lists", href: "/descriptionlists" },
  { name: "Stat Cards", href: "/statcards" },
  { name: "Grid Lists", href: "/gridlists" },
  { name: "Stacked Lists", href: "/stackedlists" },
  { name: "Tables", href: "/tables" },
];
